"""Add AICorrection model for active learning

Revision ID: 0651e6bb8b05
Revises: 7b89ab9e5455
Create Date: 2026-02-01 08:26:02.205360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0651e6bb8b05'
down_revision: Union[str, Sequence[str], None] = '7b89ab9e5455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_corrections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_ai_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corrected_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correction_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('investigator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('embeddings_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_corrections_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_corrections_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_corrections_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_corrections_entity_id'))

    op.drop_table('ai_corrections')
    # ### end Alembic commands ###
