"""Add MFA fields to User model

Revision ID: 1239ad0c1d06
Revises: 21eab98782c5
Create Date: 2026-01-31 02:08:45.180576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1239ad0c1d06'
down_revision: Union[str, Sequence[str], None] = '21eab98782c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgetline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('unit_price_cco', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('qty_cco', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_price_cco', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('requires_justification',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_budgetline_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('budgetline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgetline_item_code'))
        batch_op.alter_column('requires_justification',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('notes')
        batch_op.drop_column('total_price_cco')
        batch_op.drop_column('qty_cco')
        batch_op.drop_column('unit_price_cco')
        batch_op.drop_column('item_code')

    # ### end Alembic commands ###
