"""Add digital signatures to IntegrityRegistry

Revision ID: 1f9b34fdd053
Revises: 0651e6bb8b05
Create Date: 2026-02-01 08:27:38.049275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f9b34fdd053'
down_revision: Union[str, Sequence[str], None] = '0651e6bb8b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrity_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digital_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('signer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['signer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrity_registry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('signer_id')
        batch_op.drop_column('digital_signature')

    # ### end Alembic commands ###
