"""Sync schema with current models

Revision ID: 355a47f0ff2e
Revises: a0c99776ef30
Create Date: 2026-01-31 22:01:16.623137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '355a47f0ff2e'
down_revision: Union[str, Sequence[str], None] = 'a0c99776ef30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Data correction for existing records before setting NOT NULL
    op.execute("UPDATE budgetline SET unit_price_cco = 0.0 WHERE unit_price_cco IS NULL")
    op.execute("UPDATE budgetline SET qty_cco = 0.0 WHERE qty_cco IS NULL")
    op.execute("UPDATE budgetline SET total_price_cco = 0.0 WHERE total_price_cco IS NULL")
    op.execute("UPDATE budgetline SET requires_justification = false WHERE requires_justification IS NULL")
    op.execute("UPDATE document SET is_pinned = false WHERE is_pinned IS NULL")
    op.execute("UPDATE fraudalert SET status = 'OPEN' WHERE status IS NULL")
    op.execute("UPDATE \"transaction\" SET verification_status = 'UNVERIFIED' WHERE verification_status IS NULL")
    op.execute("UPDATE \"transaction\" SET quantity = 0.0 WHERE quantity IS NULL")
    op.execute("UPDATE \"transaction\" SET is_inferred = false WHERE is_inferred IS NULL")
    op.execute("UPDATE \"transaction\" SET is_pinned = false WHERE is_pinned IS NULL")
    op.execute("UPDATE \"user\" SET mfa_enabled = false WHERE mfa_enabled IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ai_feedback_session_id'), ['session_id'], unique=False)
        batch_op.drop_column('query_id')
        batch_op.drop_column('comment')
        batch_op.drop_column('category')

    with op.batch_alter_table('banktransaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banktransaction_batch_reference'), ['batch_reference'], unique=False)
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('budgetline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('unit_price_cco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('qty_cco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('total_price_cco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('requires_justification',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_budgetline_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chain_of_custody_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('embeddings_json', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_case_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['sealed_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_bank_account_number'), ['bank_account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_tax_id'), ['tax_id'], unique=False)

    with op.batch_alter_table('fraudalert', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
        batch_op.alter_column('metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('contract_exchange_rate',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('UNVERIFIED', 'VERIFIED', 'EXCLUDED', name='verificationstatus'),
               nullable=False,
               postgresql_using='verification_status::verificationstatus')
        batch_op.alter_column('quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('aml_stage',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PLACEMENT', 'LAYERING', 'INTEGRATION', name='amlstage'),
               existing_nullable=True,
               postgresql_using='aml_stage::amlstage')
        batch_op.alter_column('is_inferred',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_transaction_batch_reference'), ['batch_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_receiver'), ['receiver'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_sender'), ['sender'], unique=False)
        batch_op.create_foreign_key(None, 'entity', ['sender_entity_id'], ['id'])
        batch_op.create_foreign_key(None, 'entity', ['receiver_entity_id'], ['id'])
        batch_op.create_foreign_key(None, 'milestone', ['milestone_id'], ['id'])
        batch_op.create_foreign_key(None, 'case', ['case_id'], ['id'])
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transaction_sender'))
        batch_op.drop_index(batch_op.f('ix_transaction_receiver'))
        batch_op.drop_index(batch_op.f('ix_transaction_batch_reference'))
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_inferred',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('aml_stage',
               existing_type=sa.Enum('PLACEMENT', 'LAYERING', 'INTEGRATION', name='amlstage'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('verification_status',
               existing_type=sa.Enum('UNVERIFIED', 'VERIFIED', 'EXCLUDED', name='verificationstatus'),
               type_=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('contract_exchange_rate',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('fraudalert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'OPEN'::character varying"))

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_tax_id'))
        batch_op.drop_index(batch_op.f('ix_entity_bank_account_number'))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_case_project_id'))
        batch_op.drop_column('embeddings_json')
        batch_op.drop_column('last_resolved_at')
        batch_op.drop_column('chain_of_custody_json')

    with op.batch_alter_table('budgetline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgetline_item_code'))
        batch_op.alter_column('requires_justification',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('total_price_cco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('qty_cco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('unit_price_cco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('item_code')

    with op.batch_alter_table('banktransaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_banktransaction_batch_reference'))

    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('query_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_ai_feedback_session_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('feedback_text')
        batch_op.drop_column('message_id')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
