"""Add indexing to audit log hash fields

Revision ID: 7b89ab9e5455
Revises: 823dacb7dcc0
Create Date: 2026-02-01 08:13:46.731631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b89ab9e5455'
down_revision: Union[str, Sequence[str], None] = '823dacb7dcc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_hash_signature'), ['hash_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_previous_hash'), ['previous_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_previous_hash'))
        batch_op.drop_index(batch_op.f('ix_auditlog_hash_signature'))

    # ### end Alembic commands ###
