"""Add project_id to Document model

Revision ID: 823dacb7dcc0
Revises: b94845a15544
Create Date: 2026-02-01 08:06:40.478061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '823dacb7dcc0'
down_revision: Union[str, Sequence[str], None] = 'b94845a15544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_project_id'))
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
