"""Consolidate transaction models

Revision ID: 9416ac1bb2e3
Revises: 355a47f0ff2e
Create Date: 2026-02-01 07:25:29.565680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9416ac1bb2e3'
down_revision: Union[str, Sequence[str], None] = '355a47f0ff2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create Enum type manually if it doesn't exist
    op.execute("CREATE TYPE transactionsource AS ENUM ('INTERNAL_LEDGER', 'BANK_STATEMENT', 'INFERRED_GAP')")

    # 2. Add columns
    op.add_column('transaction', sa.Column('source_type', sa.Enum('INTERNAL_LEDGER', 'BANK_STATEMENT', 'INFERRED_GAP', name='transactionsource'), nullable=True))
    op.add_column('transaction', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('booking_date', sa.DateTime(), nullable=True))

    # 3. Initialize source_type for existing records
    op.execute("UPDATE \"transaction\" SET source_type = 'INTERNAL_LEDGER' WHERE source_type IS NULL")
    op.execute("UPDATE \"transaction\" SET source_type = 'INFERRED_GAP' WHERE is_inferred = true")
    
    # 4. Set source_type to NOT NULL after initialization
    op.alter_column('transaction', 'source_type', nullable=False)

    # 5. Migrate data from banktransaction to transaction
    op.execute("""
        INSERT INTO "transaction" (
            id, project_id, amount, actual_amount, proposed_amount, currency, original_currency,
            sender, receiver, description, transaction_date, timestamp, 
            batch_reference, embeddings_json, bank_name, booking_date, source_type, status, verification_status
        )
        SELECT 
            id, project_id, amount, amount, 0, currency, currency,
            'BANK_UNKNOWN', 'BANK_UNKNOWN', description, "timestamp", "timestamp",
            batch_reference, embeddings_json, bank_name, booking_date, 'BANK_STATEMENT', 'COMPLETED', 'UNVERIFIED'
        FROM banktransaction
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('booking_date')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
