"""Initial schema

Revision ID: 9ec1d705c983
Revises:
Create Date: 2026-01-29 13:15:16.466894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9ec1d705c983"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("INFO", "SUCCESS", "WARNING", "ERROR", "ALERT", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notification_user_id"), ["user_id"], unique=False)

    op.create_table(
        "userfeedback",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transaction_receiver"), ["receiver"], unique=False)
        batch_op.create_index(batch_op.f("ix_transaction_sender"), ["sender"], unique=False)

    with op.batch_alter_table("user_project_access", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_project_access_project_id"))
        batch_op.drop_index(batch_op.f("ix_user_project_access_user_id"))
        batch_op.drop_column("id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_project_access", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.VARCHAR(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_user_project_access_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_project_access_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_sender"))
        batch_op.drop_index(batch_op.f("ix_transaction_receiver"))

    op.drop_table("userfeedback")
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_user_id"))
        batch_op.drop_index(batch_op.f("ix_notification_project_id"))

    op.drop_table("notification")
    # ### end Alembic commands ###
