"""Add LLMKey model

Revision ID: a9f3f0ba97ba
Revises: d742f5c60f20
Create Date: 2026-02-01 10:18:08.485629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f3f0ba97ba'
down_revision: Union[str, Sequence[str], None] = 'd742f5c60f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llmkey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llmkey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llmkey_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_llmkey_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llmkey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llmkey_provider'))
        batch_op.drop_index(batch_op.f('ix_llmkey_alias'))

    op.drop_table('llmkey')
    # ### end Alembic commands ###
