"""Sync DB with Models: Remove case_id and aml_stage from Transaction

Revision ID: d742f5c60f20
Revises: 1f9b34fdd053
Create Date: 2026-02-01 09:29:08.907763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd742f5c60f20'
down_revision: Union[str, Sequence[str], None] = '1f9b34fdd053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_case_id_fkey', type_='foreignkey')
        batch_op.drop_column('case_id')
        batch_op.drop_column('aml_stage')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aml_stage', postgresql.ENUM('PLACEMENT', 'LAYERING', 'INTEGRATION', name='amlstage'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('transaction_case_id_fkey', 'case', ['case_id'], ['id'])

    # ### end Alembic commands ###
